## Wifi
CIRCUITPY_WIFI_SSID = "<your network>"
CIRCUITPY_WIFI_PASSWORD = "<your password>"

## Data collection constants
# Choose a unique device ID for your device, e.g. "yourname-co2-temperature"
DEVICE_ID = None

# Set a location (recommended: "indoors" or "outdoors").
# You can be more specific, but:
# - don't include anything you're not willing to share with the class.
# - still include the word "indoors" or "outdoors" so that fellows can string-match.
LOCATION = "not set"

# Public/anonymous connection info for our supabase instance
# (Yep, we've just put the access key in plaintext here :o )
SUPABASE_POST_URL = "https://quakzdcsawtiigpkqcmp.supabase.co/rest/v1/iot"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1YWt6ZGNzYXd0aWlncGtxY21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczOTgxNzUsImV4cCI6MjA1Mjk3NDE3NX0.VyBLZCYygtiQn4jy7hmtExQOI3a12biu_H4B8s3QAOM"
