## Wifi
CIRCUITPY_WIFI_SSID = "<your network>"
CIRCUITPY_WIFI_PASSWORD = "<your password>"

## Data collection constants
# Choose a unique device ID for your device, e.g. "yourname-co2-temperature"
DEVICE_ID = None

# Public/anonymous connection info for our supabase instance
# (Yep, we've just put the access key in plaintext here :o )
SUPABASE_POST_URL = "https://jvnfqnseyxaiiybpxzrt.supabase.co/rest/v1/iot"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2bmZxbnNleXhhaWl5YnB4enJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTEzODU2MDgsImV4cCI6MjAyNjk2MTYwOH0.dFUNhtOkzF2wf-k42qAvj-O2LKJiCbFIEkCPf5im5tg"
