## Wifi
CIRCUITPY_WIFI_SSID = "<your network>"
CIRCUITPY_WIFI_PASSWORD = "<your password>"

## Data collection constants
# Choose a unique device ID for your device, e.g. "yourname-co2-temperature"
DEVICE_ID = None

# Set a location (recommended: "indoors" or "outdoors").
# You can be more specific, but:
# - don't include anything you're not willing to share with the class.
# - still include the word "indoors" or "outdoors" so that fellows can string-match.
LOCATION = "not set"

# Public/anonymous connection info for our supabase instance
# Get these from the assignment instructions
SUPABASE_POST_URL = ""
SUPABASE_KEY = ""