name: Device Data Monitor

on:
  schedule:
    - cron: '0 16 * * *'  # 8 AM Pacific
    - cron: '0 20 * * *'  # 12 PM Pacific
    - cron: '0 1 * * *'   # 5 PM Pacific (next day UTC)
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv venv
        uv pip install supabase python-dotenv python-dateutil
    
    - name: Run device monitor
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: uv run python device_monitor.py 