name: Device Data Monitor

on:
  schedule:
    - cron: '0 8 * * *'  # 8 AM UTC
    - cron: '0 12 * * *' # 12 PM UTC
    - cron: '0 17 * * *' # 5 PM UTC
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv pip install supabase python-dotenv python-dateutil
    
    - name: Run device monitor
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python device_monitor.py 